version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: Qdrant-container
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage  # volume: qdrant_data - 컨테이너 내 경로: /qdrant/storage 매핑
    environment:
      - QDRANT__STORAGE__PATH=/qdrant/storage

volumes:
  qdrant_data:
    driver: local
